# FROM grafana/latest-ubuntu
FROM grafana/grafana:10.4.1-ubuntu

# Grafana GUI Customisation #
#############################
USER root

# Grafana Theme Change
ENV GF_USERS_DEFAULT_THEME=light

# Setting Back Normal User
USER grafana 

